auFifo   : 64
auNum    : 10
dAdd     : 3
input    : 'dataset/shapes.mat'
name     : 'shapes_hash_'
tDel     : 2
areaDel  : 64
tLive    : 3
areaLive : 256
numLive  : 40
epsDiv   : 22
iomMer   : 0.1
dsMer    : 30
outfolder: 'result'
merge    : 'IOM'
split    : 'DBSCAN'
bitfile  : 'bitfile/hash_64_3_10.bit'