auFifo   : 100
auNum    : 20
dAdd     : 2
input    : 'dataset/shapes.mat'
name     : 'shapes'
tDel     : 2
areaDel  : 64
tLive    : 3
areaLive : 256
numLive  : 40
epsDiv   : 22
iomMer   : 0.1
dsMer    : 30
outfolder: 'result'
merge    : 'IOM'
split    : 'DBSCAN'